name: array
version: 1.0

executables:
  linux:
    amd64: index-linux
  darwin:
    amd64: index-macos

steps:
  find@1.0:
    inputs:
      Records:
        required: true
        description: The list of records you would like to search through
      MatchField:
        required: true
        description: The field that you would like to match on
      MatchValue:
        required: true
        description: The value you would like to match on
    outputs:
      Record:
        description: The first record encountered whose field matched, null if no match
  first@1.0:
    inputs:
      Records:
        required: true
        description: The list of records
    outputs:
      IsEmpty:
        description: Whether the array was empty. If this is set to `true` then `Record` will be nil
      Record:
        description: The first record in the array if the size of the array is > 0
  insert_object@1.0:
    inputs:
      Records:
        required: true
        description: The list of records you want to add to
      Object:
        required: true
        description: The record(s) that you would like to add to the list of records it could be a single object or an array
    outputs:
      Records:
        description: The new list of records
  remove_object@1.0:
    inputs:
      Records:
        required: true
        description: The list of records you want to remove a record from
      MatchField:
        required: false
        description: The field that you would like to match on in order to remove
      MatchValue:
        required: false
        description: The value you would like to match on in order to remove
      Index:
        required: false
        description: The index of the item/object to remove if not removing by key/value
    outputs:
      Records:
        description: The new list of records