name: google_auth
version: 1.0

steps:
  get_token@1.0:
    inputs:
      Credential:
        required: true
        description: Your google cloud service account
        sample: '{"key" : "value"}'
      Scopes:
        required: true
        description: The scopes you want to request
        sample: '["https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/sqlservice.admin"]'
    outputs:
      Token:
        description: The access token (lasts for 60 min)
