name: object
version: 1.0

executables:
  linux:
    amd64: index-linux
  darwin:
    amd64: index-macos

steps:
  new@1.0:
    inputs:
      Fields:
        required: true
        description: A map of key values to set on the newly created object
        sample: |
          Name: Matt
          Age: 35
    outputs:
      Record:
        description: The newly created object with [Fields] set.
  update@1.0:
    inputs:
      Fields:
        required: true
        description: A map of key values to set on the newly created object
        sample: |
          Name: Matt
          Age: 35
      Record:
        required: true
        description: The record to update
        sample: '{ "Name": "Matt" }'
    outputs:
      Record:
        description: "The record with [Fields] applied to it"
