name: google_sheets
version: 1.0

runtime: go #the language the package is in

executables:
  linux:
    amd64: main_linux_amd64
  darwin:
    amd64: main_darwin_amd64
  windows:
    amd64: main_windows_amd64.exe

#The steps in this package
steps:
  read@1.0:
    description: Read from a google sheet
    inputs:
      SpreadsheetId:
        required: true
        description: "The ID of the Google Spreadsheet"
        sample: XD23223211212
      SheetIndex:
        required: false
        description: "The index of the sheet you want to use. Defaults to the first sheet."
        sample: 0
      Credentials:
        required: true
        description: "Your Google Sheets credentials JSON. To create your credentials see https://developers.google.com/sheets/api/quickstart/go"
        sample: '{}'
      Fields:
        required: true
        description: "The names of the fields in the order they are defined within the spreadsheet"
        sample: |
          - firstName
          - lastName
          - email
    outputs:
      Rows:
        description: "The output of each row"
  write@1.0:
    description: Write to a Google sheet
    inputs:
      SpreadsheetId:
        required: true
        description: "The ID of the Google Spreadsheet"
        sample: XD23223211212
      SheetIndex:
        required: false
        description: "The index of the sheet you want to use. Defaults to the first sheet."
        sample: 0
      Credentials:
        required: true
        description: "Your Google Sheets credentials JSON. To create your credentials see https://developers.google.com/sheets/api/quickstart/go"
        sample: '{}'
      Cells:
        required: true
        description: "The string values you want to write to each row, in order"
        sample: |
          - "NewRecord"
          - ${SomeVar}
          - "August10"
      MatchValue:
        required: false
        description: "The value used to identify the record to update"
      MatchColumn:
        required: false
        description: "The db column used to identify the record to update"
