name: google_sheets
version: 1.0

runtime: go #the language the package is in

executables:
  linux:
    amd64: main_linux_amd64
  darwin:
    amd64: main_darwin_amd64
  windows:
    amd64: main_windows_amd64.exe

inputBase: &input_base
  SpreadsheetId:
    required: true
    description: "The ID of the Google Spreadsheet"
    sample: XD23223211212
  SheetIndex:
    required: false
    description: "The index of the sheet you want to use. Defaults to the first sheet."
    sample: 0
  Credentials:
    required: true
    description: "Your Google Sheets credentials JSON. To create your credentials see https://developers.google.com/sheets/api/quickstart/go"
    sample: '{}'
  SheetName:
    required: false
    description: "The name of the sheet"
    sample: "Sheet1"


#The steps in this package
steps:
  read@1.0:
    description: Read from a google sheet
    inputs:
      <<: *input_base
      Fields:
        required: true
        description: "The names of the fields in the order they are defined within the spreadsheet"
        sample: |
          - firstName
          - lastName
          - email
      Ranges:
        required: false
        description: A list of ranges to limit read too
        sample: |
          - A1:D
    outputs:
      Rows:
        description: "The output of each row"
  write@1.0:
    description: Write to a Google sheet
    inputs:
      <<: *input_base
      Cells:
        required: true
        description: "The string values you want to write to each row, in order"
        sample: |
          - "NewRecord"
          - ${SomeVar}
          - "August10"
      MatchValue:
        required: false
        description: "The value used to identify the record to update"
      MatchColumn:
        required: false
        description: "The db column used to identify the record to update"
  read_rows_and_queue@1.0:
    description: Read rows from a google sheet and queue new workflows from each
    inputs:
      SpreadsheetId:
        required: true
        description: "The ID of the Google Spreadsheet"
        sample: XD23223211212
      SheetIndex:
        required: false
        description: "The index of the sheet you want to use. Defaults to the first sheet."
        sample: 0
      Credentials:
        required: true
        description: "Your Google Sheets credentials JSON. To create your credentials see https://developers.google.com/sheets/api/quickstart/go"
        sample: '{}'
      Fields:
        required: true
        description: "The names of the fields in the order they are defined within the spreadsheet"
        sample: |
          - firstName
          - lastName
          - email
      Workflow:
        required: true
        description: The workflow that you want to queue up
  batch_write@1.0:
    description: Write a list of objects to a sheet
    inputs:
      <<: *input_base
      Records:
        required: true
        description: "The list of object fields to be inserted. These should be ordered exactly as you want them to appear in the sheet."
        sample: |
          [{"username": "billy", "name": "Billy Jean"},{"username": "user1": "name": "Betty Sue"}]
      ClearSheet:
        required: false
        description: "A flag indicating if sheet should be cleared before records are synced."
      MatchColumn:
        required: false
        description: "The column index to match new values on if updating records rather than appending all records"
        sample: "username"
      Update:
        required: true
        description: "A flag indicating if you would like to update records using the match column value or if they should just be appended"
      Fields:
        required: true
        description: "A map of column indexes to their matched field name"
        sample: |
          0: username
          1: name
    outputs:
      RecordsCreated:
        description: "The count of records created"
      RecordsUpdated:
        description: "The count of records updated"
  cache_batch_write@1.0:
    description: Write a list of objects to a sheet
    inputs:
      <<: *input_base
      ClearSheet:
        required: false
        description: "A flag indicating if sheet should be cleared before records are synced."
      MatchColumn:
        required: false
        description: "The column index to match new values on if updating records rather than appending all records"
        sample: "username"
      Update:
        required: true
        description: "A flag indicating if you would like to update records using the match column value or if they should just be appended"
      Fields:
        required: true
        description: "A map of column indexes to their matched field name"
        sample: |
          0: username
          1: name
      Filter:
        required: true
        description: "The filter to use for fetching records from cache"
        sample: '{"Group": "test"}'
      CacheName:
        required: true
        description: "The name of the cache to pull records from"
        sample: "MyTestCache"
    outputs:
      RecordsCreated:
        description: "The count of records created"
      RecordsUpdated:
        description: "The count of records updated"

