name: json
version: 1.0

executables:
  linux:
    amd64: index-linux
  darwin:
    amd64: index-macos

steps:
  parse@1.0:
    inputs:
      String:
        required: true
        description: The text you want to parse as JSON
        sample: '{"key" : "value"}'
    outputs:
      Record:
        description: The record that was parsed from the JSON string
  parse_array@1.0:
    inputs:
      String:
        required: true
        description: "A string representing a json array of records to parse"
        sample: '["value1", "value2"]'
    outputs:
      Records:
        description: The json array parsed from the input `text`
