name: famis
version: 1.0
lang: go
executables:
  windows:
    amd64: main_windows_amd64.exe
steps:
  create_request@1.0:
    description: Create a request in famis
    inputs:
      ConnectionString:
        required: true
        sample: "oracle://user:passw@service_name OR user/passw@service_name OR advanced connection user/pass@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=tcp)(HOST=hostname)(PORT=port)))(CONNECT_DATA=(SERVICE_NAME=sn)))"
        description: Oracle Connection string
      Requester:
        required: true
        sample: STERLING, KEVIN
        description: The user making the request
      SiteId:
        required: true
        sample: 00851
        description: The ID of the site
      Description:
        required: true
        sample: There is a pothole that is approx. 2 inches wide
        description: A description of the problem
      AttachmentUrl:
        required: false
        sample: https://google.com/image.png
        description: The url for an attachment
      Notes:
        required: false
        sample: "Turned oven off and back on, Rotated the cuff"
        description: A note to add to the request
      EquipmentId:
        required: false
        sample: E4569566
        description: The piece of equipment you are working on
      RequestStatus:
        required: true
        sample: REQUESTESD
        description: the request status
      RequestType:
        required: true
        sample: S
        description: the request type
      MaintenanceType:
        required: true
        sample: CORRECTIVE
        description: the maintenance type
      Priority:
        required: true
        sample: '3'
        description: the priority that should be assigned to this request
      EnterUser:
        required: true
        sample: APPTREEIO
        description: the user entering this ticket
      NeedNotification:
        required: true
        sample: false
        description: a flag indicating if this request needs a notification to be sent
      RequestSource:
        required: true
        sample: ASSISTANT
        description: the source which the requester is creating this request from
    outputs:
      ServiceRequestId:
        description: the Id of the created service request