name: postgres
version: 1.0
lang: go
executables:
  linux:
    amd64: main_linux_amd64
  darwin:
    amd64: main_darwin_amd64
  windows:
    amd64: main_windows_amd64.exe
steps:
  insert_batch@1.0:
    description: "Accepts a list of records and inserts them into a database."
    inputs:
      Sql:
        required: true
        description: "The insert statement you'd like to perform"
        sample: "INSERT INTO my_table VALUES ($1,$2)"
      Records:
        required: true
        description: "The list of records you'd like to insert"
        sample: myvar
      Fields:
        required: true
        description: "The field names you'd like to pull from from the `Records` input."
        sample: |
          - firstName
          - lastName
  execute@1.0:
    description: "Accepts a list of records and inserts them into a database."
    inputs:
      ConnectionString:
        required: true
        sample: "postgres://user:passw@localhost:5432"
        description: "Postgres Connection string"
      Sql:
        required: true
        description: ""
  mock_execute@1.0:
    description: "Accepts a list of records and inserts them into a database."
    inputs:
      ConnectionString:
        required: true
        sample: "postgres://user:passw@localhost:5432"
        description: "Postgres Connection string"
      Sql:
        required: true
        description: ""
  query@1.0:
    description: "Performs a SELECT query"
    inputs:
      ConnectionString:
        required: true
        sample: "postgres://user:passw@localhost:5432"
        description: "Postgres Connection string"
      Sql:
        required: true
        description: ""
    outputs:
      Results:
        description: "The records returned from the query."
  query_and_queue@1.0:
    description: "Performs a SELECT query. All rows returned will get queued to run as part of another workflow"
    inputs:
      ConnectionString:
        required: true
        sample: "postgres://user:passw@localhost:5432"
        description: "Postgres Connection string"
      Sql:
        required: true
        description: ""
      Workflow:
          required: true
          description: "The workflow you want to run. This workflow must be part of your project"
          sample: "process_results"
    outputs:
      Results:
        description: "The records returned from the query."
  import_csv@1.0:
    description: "Accepts a list of records and inserts them into a database."
    inputs:
      ConnectionString:
        required: true
        sample: "postgres://user:passw@localhost:5432"
        description: "Postgres Connection string"
      TableName:
        required: true
        description: "The table to insert into"
      Fields:
        required: true
        description: A list of keys and values where they key indicates which column to insert into, and the value is the index to use in the CSV file
        sample: |
          - column1:4:text
          - column2:3:integer
      SkipFirst:
        required: false
        description: Skip the first row of data in the CSV
      ClearTable:
        required: false
        description: Whether the table should be cleared prior to insert
    outputs:
      RecordCount:
        description: The number of records processed
      Duration:
        description: How long the import took