name: io_assistant
version: 1.0
lang: go

executables:
  linux:
    amd64: main_linux_amd64
  darwin:
    amd64: main_darwin_amd64
  windows:
    amd64: main_windows_amd64.exe

steps:
  create_message@1.0:
    inputs:
      message:
        required: true
        description: The message object to pass back
        sample: '{"type": "promptText, "text": "What does the control panel say?", "id": "controlPanelOutput"}'
      userContext:
        required: false
        description: a map of value to add to the user context which will persist across interactions
        sample: '{"store": "userStore3"}'
      context:
        required: false
        description: a map of values to add to the context
        sample: '{"onThreadCompleteUrl": "https://example.com"}'
      complete:
        required: false
        description: a bool indicating that this message should mark the conversation as complete
    outputs:
      response:
        description: the fulfillment response that has been formatted and validated for the io assistant
  create_message_group@1.0:
    inputs:
      messages:
        required: true
        description: The group to pass back
        sample: '[{"id": "sampleMessage", "type": "promptBool", "text": "Do you love the AppTree assistant?"}]'
      userContext:
        required: false
        description: a map of value to add to the user context which will persist across interactions
        sample: '{"store": "userStore3"}'
      context:
        required: false
        description: a map of values to add to the context
        sample: '{"onThreadCompleteUrl": "https://example.com"}'
    outputs:
      response:
        description: the fulfillment response that has been formatted and validated for the io assistant
  parse_fulfillment@1.0:
    inputs:
      bodyAsString:
        required: true
        description: the request body from the io assistant as a string
        sample: '{"state": {"controlPanelOutput": "error_code_01"}, "userContext": {"store": "userStore3"}, "context": {"onThreadCompleteUrl": "https://example.com"}}'
    outputs:
      request:
        description: the body parse to a fulfillment request which has state, userContext, and context maps
  build_select_options@1.0:
    inputs:
      records:
        required: true
        description: the list of records that you would like to build assistant select options from
      idField:
        required: true
        description: the name of the field that should be used as the select option ID
      textField:
        required: true
        description: the name of the field that should be displayed for the select option
    outputs:
      options:
        description: the list of records formatted as select options for an assistant message
  build_options_list@1.0:
    inputs:
      records:
        required: true
        description: the list of strings that you would like to convert to a select list
    outputs:
      options:
        description: the list of records formatted as select options for an assistant message

